image: gradle:alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
    - build
    - test

test:
    stage: test
    script: ./gradlew check
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - .gradle

assembleDebug:
    stage: build
    script:
        - ./gradlew assembleDebug
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - .gradle

#lintDebug:
#  stage: build
#  script:
#    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
#
#assembleDebug:
#  stage: build
#  script:
#    - ./gradlew assembleDebug
#  artifacts:
#    paths:
#    - app/build/outputs/
#
#debugTests:
#  stage: test
#  script:
#    - ./gradlew -Pci --console=plain :app:testDebug
